import { StyleSheet } from "react-native";
import { TEMA } from "../utils/temaApp";

export const globalStyles = StyleSheet.create({
  contenedorSafeArea: {
    flex: 1,
    backgroundColor: TEMA.negro,
  },
  contenedorCabecera: {
    paddingLeft: 10,
    paddingRight: 8,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: 3,
    borderBottomColor: TEMA.rojo,
    backgroundColor: TEMA.negroElevado,
  },
  /** Logo TavernMaster: espacio lateral y centrado; algo más pequeño que en login. */
  contenedorLogoCabecera: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    minWidth: 0,
  },
  contenedorDatosUsuario: {
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: TEMA.cremaClaro,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: TEMA.negro,
    shadowColor: TEMA.negro,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
  },
  contenedorEtiqueta: {
    backgroundColor: TEMA.negro,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 3,
    borderBottomColor: TEMA.rojo,
  },
  contenedorBotones: {
    flexDirection: "row",
    gap: 16,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  barraAccionesLista: {
    flexDirection: "row",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "stretch",
  },
  botonGenerico: {
    backgroundColor: TEMA.cremaClaro,
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: TEMA.negro,
    alignItems: "center",
    justifyContent: "center",
  },
  contenedorImagenUsuario: {
    position: "relative",
    width: 80,
    height: 80,
  },
  contenedorPrincipal: {
    flex: 1,
    backgroundColor: TEMA.crema,
    paddingVertical: 20,
  },
  botonRojo: {
    backgroundColor: TEMA.rojo,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 80,
    borderWidth: 2,
    borderColor: TEMA.negro,
  },
  botonAmarillo: {
    backgroundColor: TEMA.cremaClaro,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 80,
    borderWidth: 2,
    borderColor: TEMA.negro,
  },
  botonVerde: {
    backgroundColor: TEMA.rojo,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 80,
    borderWidth: 2,
    borderColor: TEMA.negro,
  },
  textoUsuario: {
    fontSize: 20,
    fontWeight: "bold",
    color: TEMA.textoNegro,
    marginBottom: 4,
  },
  textoEtiqueta: {
    fontSize: 24,
    fontWeight: "bold",
    color: TEMA.textoCrema,
    textAlign: "center",
  },
  textoBoton: {
    color: TEMA.textoCrema,
    fontWeight: "600",
    fontSize: 15,
  },
  textoBotonSobreCrema: {
    color: TEMA.textoNegro,
    fontWeight: "600",
    fontSize: 15,
  },
  imagenLogo: {
    width: 120,
    height: 120,
  },
  /** Solo cabecera principal (lista); deja margen visual alrededor del asset. */
  imagenLogoCabecera: {
    width: 92,
    height: 92,
  },
  imagenUsuario: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: TEMA.rojo,
  },
  contenedorCard: {
    flex: 1,
    marginLeft: 4,
  },
  nombreCard: {
    fontSize: 18,
    fontWeight: "bold",
    color: TEMA.textoNegro,
    marginBottom: 6,
  },
  filaCard: {
    flexDirection: "row",
    marginVertical: 1,
  },
  atributoPersonaje: {
    fontSize: 14,
    fontWeight: "600",
    color: TEMA.rojoOscuro,
    width: 70,
  },
  valorAtributo: {
    fontSize: 14,
    color: TEMA.textoSecundario,
    flex: 1,
  },
  barraBusqueda: {
    marginHorizontal: 10,
    marginBottom: 10,
    padding: 10,
    backgroundColor: TEMA.cremaClaro,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: TEMA.negro,
    fontSize: 16,
    color: TEMA.textoNegro,
  },
  imagenModal: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: TEMA.negro,
  },
});
