import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({

  contenedorSafeArea: {
    flex: 1,
    backgroundColor: '#F5E6D3',
  },
  contenedorCabecera: {
    backgroundColor: '#F5E6D3',
    paddingHorizontal: 20,
    paddingVertical: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: '#D4B896',
  },
  contenedorDatosUsuario: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    backgroundColor: '#FFF9F0',
    padding: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#D4B896',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  contenedorEtiqueta: {
    backgroundColor: '#8B6F47',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#6B5537',
  },
  contenedorBotones: {
    flexDirection: 'row',
    gap: 16,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  contenedorImagenUsuario: {
    position: 'relative',
    width: 80,
    height: 80,
  },
  contenedorPrincipal: {
    flex: 1,
    backgroundColor: '#F5E6D3',
    paddingVertical: 20,
  },
  botonRojo: {
    backgroundColor: '#8B0000',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
  },
  botonAmarillo: {
    backgroundColor: '#DAA520',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
  },
  botonVerde: {
    backgroundColor: '#2E8B57',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
  },
  textoUsuario: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#8B4513',
    marginBottom: 4,
  },
  textoEtiqueta: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
  },
  textoBoton: {
    color: 'white',
    fontWeight: '600',
    fontSize: 15,
  },
  imagenLogo: {
    width: 120,
    height: 120,
  },
  imagenUsuario: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
    cardPersonaje: {
    backgroundColor: '#FFF9F0',
    borderRadius: 8,
    padding: 12,
    marginHorizontal: 16,
    marginVertical: 6,
    borderWidth: 1,
    borderColor: '#D4B896',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  imagenPersonaje: {
    width: 70,
    height: 70,
    borderRadius: 35,
    marginRight: 12,
    borderWidth: 2,
    borderColor: '#8B6F47',
  },
  contenedorCard: {
    flex: 1,
    marginLeft: 4,
  },
  nombreCard: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#8B4513',
    marginBottom: 6,
  },
  filaCard: {
    flexDirection: 'row',
    marginVertical: 1,
  },
  atributoPersonaje: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8B6F47',
    width: 70,
  },
  valorAtributo: {
    fontSize: 14,
    color: '#5D4037',
    flex: 1,
  },
});